### ISSUE TITLE
How can I get this to work on a Mac?

### ISSUE THREAD

**Issue by b-a0** [qmasingarbe/pymiere#11]
From the function in `exe_utils.py` I understand this library is written for Windows. 

Does anybody know if (and how) I can change this so it works on a Mac?

**Comment by qmasingarbe** [comment]
Pymiere is currently only supported on Windows, most of the exe_utils.py code is indeed windows specific and other part of the code may not be compatible.
As I don't own a Mac, I can't help you with this issue... You could try to reimplement the exe_utils code yourself and I will gladly merge it into the project.

**Comment by BigRoy** [comment]
@qmasingarbe would you happen to know whether the `.zxp` files (specifically the Adobe add-on) itself would be cross-OS compatible? If that's the case, I can set up a branch for you @b-a0 where you'd just have to point to the Premiere executable with an environment variable, e.g. `PYMIERE_PREMIERE_EXECUTABLE` so that it skips all the `exe_utils` where it tries to retrieve it automagically.

The only other thing would be to cross-OS check whether Premiere is currently running and swapping it out [here](https://github.com/qmasingarbe/pymiere/blob/a41a879edf1c2dd419f8b8f914d030826a6dbbfd/pymiere/core.py#L29). Which could be doing [either `pgrep`](https://stackoverflow.com/a/22985328/1838864) or [using something like `psutil`](https://stackoverflow.com/a/22985099/1838864).

Unfortunately I don't have Mac either to test it out, so developing it would be hard to "debug and try".
What's your programming level @b-a0? I'd be happy to see if some hints could point you in the right direction.

**Comment by b-a0** [comment]
@BigRoy Thanks for thinking with me and offering your help. My programming level is hard to gauge, I can comfortably create scripts with high level libraries like `pandas` and `plotly` and can do some batch work with bash and powershell, but have little experience with proper (object oriented) programming. 
I think I could manage setting environment variables and checking if Premiere is running though, so let me know if we can forward with this.

In the meantime I've downloaded VSCode to use ExtendScript directly, but I think it would still be nice to make `pymiere` compatible with OS X.

**Comment by fixinPost** [comment]
Hi I'm a big fan of you're  work @b-a0, I feel like pymiere can fundamentally change Premiere Pro workflows, so if there's anything I can do to help with porting it to OS X, I offer my help. I have some python experience and a macbook with Catalina I could help test or research.

**Comment by qmasingarbe** [comment]
I @fixinPost , thanks for offering your help!
Can you start by installing the [Premiere Pro extension](https://github.com/qmasingarbe/pymiere/blob/master/pymiere_link.zxp) for pymiere (multiple installation method can be found in the [readme](https://github.com/qmasingarbe/pymiere/blob/tests/README.md) )
Then download the pymiere python lib from [the tests branch](https://github.com/qmasingarbe/pymiere/tree/tests) of this repo where I bypassed some code for non Windows system.
Try running some basic code like
```
import pymiere
print(pymiere.objects.app.isDocumentOpen())
```
Let me know if thoses steps worked well. We will then try to go further.

**Comment by qmasingarbe** [comment]
Hi @fixinPost @b-a0  @BigRoy ,
**It works!**
I've been busy for the last few days figuring out how to make `pymiere `work on macOS and finally managed to sort everything out!

I installed a VM running `macOS Catalina` and did a bunch of testing and development. The lib and all the demos are now working on mac and I updated the readme with installation instructions.

The new version is available via pip.
Please open an issue or send me an email if any bugs or weird behavior appear on mac and we will figure them out.

Many thanks

**Comment by b-a0** [comment]
Fantastic, I've tested [demo.py](https://github.com/qmasingarbe/pymiere/blob/master/demo.py) and everything works!

**Comment by SergiHernandez** [comment]
So the exe_utils functions are developed and tested to be compatible for both Windows and macOS.
But (as an inexperienced guy in operative systems and libraries) my question is: should the other functions work fine regardless of the operative system?
I mean the functions related to actual premiere workflows once it is running (importing media, exporting media, placing media in the timeline...).
Thanks in advance.

**Comment by qmasingarbe** [comment]
Hi @SergiHernandez everything should work on both platform including the Premiere Pro part. I tested all the example code on Mac as well as on Windows. The only difference is the path syntax on Windows that must use backslashes rather than simple slashes on Mac for python to work with.

**Comment by SergiHernandez** [comment]
@qmasingarbe Perfect!! Thanks for the clarification.
