### ISSUE TITLE
Wrong path for get_installed_software_info function

### ISSUE THREAD

**Issue by qmasingarbe** [qmasingarbe/pymiere#6]
Also, got issue with the get_installed_software_info() function inside exe_utils, the function returned a bad path or incomplete

so in  get_installed_software_info() function I changed:
exe_path = last_version_info["InstallLocation"]
into:
exe_path = last_version_info["InstallLocation"]+'\\' +last_version_info["DisplayName"]

Cause in Premiere Pro 14.x the path returned in "InstallLocation" is incomplete

_Originally posted by @bryhimself in https://github.com/qmasingarbe/pymiere/issues/3#issuecomment-668169416_

**Comment by BigRoy** [comment]
I'm hitting this issue but for me the issue is that it hits this error:

```python
# Error: Could not find install dir for Premiere in 'C:\Program Files\Adobe\Adobe Premiere Pro CC 2020'
# Traceback (most recent call last):
#   File "<maya console>", line 4, in <module>
#   File "C:\Users\Roy\Downloads\pymiere-master\pymiere\exe_utils.py", line 115, in start_premiere
#     exe_path = get_last_premiere_exe()
#   File "C:\Users\Roy\Downloads\pymiere-master\pymiere\exe_utils.py", line 99, in get_last_premiere_exe
#     raise IOError("Could not find install dir for Premiere in '{}'".format(exe_path))
# IOError: Could not find install dir for Premiere in 'C:\Program Files\Adobe\Adobe Premiere Pro CC 2020' # 
```

Where the actual folder does not contain `CC` in the name, so it is: `C:\Program Files\Adobe\Adobe Premiere Pro 2020`.

Which seems to be added in the code by [this line](https://github.com/qmasingarbe/pymiere/blob/master/pymiere/exe_utils.py#L96). Removing CC there makes `start_premiere` function as expected for me.

**Comment by qmasingarbe** [comment]
Different versions of Premiere have different install paths, I fixed this part to take into account all possible install pattern.
