### ISSUE TITLE
ProjectItem.setProjectMetadata() needs 2 arguments

### ISSUE THREAD

**Issue by stephen-kim** [qmasingarbe/pymiere#64]
According to scripting guide written by Adobe, ProjectItem.setProjectMetadata() needs 2 arguments. Serialized XMP-like metadata, and a list of field name that needs to be updated.
But pymiere accepts only one parameter - 'buffer'.
Unlike setXMPMetadata(), this gives me an error.
Am I missing something?

**Comment by qmasingarbe** [comment]
Hi @stephen-kim ,
Thank you for reporting this issue, there was indeed a mistake in Pymiere method declaration for setProjectMetadata. This has been fixed by d890b847b5e45527cd0f16ac6703a83d388ee095 and is available in the last 1.4.1 version via pip.
Again thank you for participating in making pymiere better!
